name: Daily Naukri Resume Upload

on:
  schedule:
    - cron: '45 1 * * *'  # 7:15 AM IST (1:45 AM UTC)
  workflow_dispatch:

jobs:
  update-resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Set environment variables
        run: echo "NAUKRI_USERNAME=${{ secrets.NAUKRI_USERNAME }}" >> $GITHUB_ENV && echo "NAUKRI_PASSWORD=${{ secrets.NAUKRI_PASSWORD }}" >> $GITHUB_ENV

      - name: Run Resume Upload Script
        run: python naukri_resume_uploader.py
