name: Upload Resume to Naukri

on:
  schedule:
    - cron: '15 1 * * *'  # Runs every day at 07:15 AM IST (01:45 UTC)
  workflow_dispatch:      # Allows manual trigger

jobs:
  upload-resume:
    runs-on: windows-latest

    env:
      USERNAME: ${{ secrets.NAUKRI_USERNAME }}
      PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Download matching ChromeDriver
        shell: pwsh
        run: |
          $chromePath = "C:\Program Files\Google\Chrome\Application\chrome.exe"
          $chromeVersion = (Get-Item $chromePath).VersionInfo.ProductVersion
          Write-Host "Detected Chrome version: $chromeVersion"
          $majorVersion = $chromeVersion.Split('.')[0]

          try {
            $driverVersion = Invoke-RestMethod "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" |
              ConvertFrom-Json |
              Select-Object -ExpandProperty channels |
              Select-Object -ExpandProperty Stable |
              Select-Object -ExpandProperty version
            Write-Host "Resolved compatible driver: $driverVersion"

            $url = "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$driverVersion/win64/chromedriver-win64.zip"
            Invoke-WebRequest $url -OutFile "chromedriver.zip"
            Expand-Archive chromedriver.zip -DestinationPath "."
            $env:Path += ";$PWD\chromedriver-win64"
          } catch {
            Write-Host "❌ Failed to resolve compatible ChromeDriver"
            exit 1
          }

      - name: Run resume uploader
        run: python naukri_resume_uploader.py
