name: Run Naukri Resume Uploader (Windows)

on:
  schedule:
    - cron: '45 1 * * *'  # 7:15 AM IST daily
  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Google Chrome
        run: choco install googlechrome --yes

      - name: Install ChromeDriver (auto-matches Chrome)
        uses: nanasess/setup-chromedriver@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Resume Uploader Script
        env:
          USERNAME: ${{ secrets.NAUKRI_USERNAME }}
          PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        run: python naukri_resume_uploader.py
