name: Run Naukri Resume Uploader

on:
  schedule:
    - cron: '45 1 * * *'  # Runs at 1:45 AM UTC → 7:15 AM IST
  workflow_dispatch:  # Also allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome 126 and matching ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl

          # Install Google Chrome 126.0.6478.57
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_126.0.6478.57-1_amd64.deb
          sudo dpkg -i google-chrome-stable_126.0.6478.57-1_amd64.deb || sudo apt-get -f install -y

          # Install matching ChromeDriver
          wget https://chromedriver.storage.googleapis.com/126.0.6478.57/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          USERNAME: ${{ secrets.NAUKRI_USERNAME }}
          PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        run: python naukri_resume_uploader.py
