name: Daily Naukri Resume Upload

on:
  schedule:
    - cron: '45 1 * * *'  # 7:15 AM IST
  workflow_dispatch:

jobs:
  update-resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium

      - name: Install Headless Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://storage.googleapis.com/chrome-for-testing-public/137.0.7151.55/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome
          sudo ln -s /opt/chrome/chrome /usr/bin/google-chrome

          wget https://storage.googleapis.com/chrome-for-testing-public/137.0.7151.70/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Set environment variables
        run: |
          echo "NAUKRI_USERNAME=${{ secrets.NAUKRI_USERNAME }}" >> $GITHUB_ENV
          echo "NAUKRI_PASSWORD=${{ secrets.NAUKRI_PASSWORD }}" >> $GITHUB_ENV

      - name: Run Naukri Resume Upload Script
        run: python naukri_resume_uploader.py
